export const SURVIVOR_50 = {
  seasonKey: "SURVIVOR_50",
  castaways: [
    { name: "Aiden Brooks", tribe: "Tide" },
    { name: "Bianca Flores", tribe: "Tide" },
    { name: "Caleb Young", tribe: "Tide" },
    { name: "Danica Park", tribe: "Tide" },
    { name: "Evan Price", tribe: "Tide" },
    { name: "Farrah Khan", tribe: "Tide" },
    { name: "Gavin Cole", tribe: "Tide" },
    { name: "Harper Wells", tribe: "Tide" },
    { name: "Isaiah Reed", tribe: "Flame" },
    { name: "Jules Carter", tribe: "Flame" },
    { name: "Kendra Shaw", tribe: "Flame" },
    { name: "Liam Ortiz", tribe: "Flame" },
    { name: "Mara Quinn", tribe: "Flame" },
    { name: "Noah Drake", tribe: "Flame" },
    { name: "Olive Bennett", tribe: "Flame" },
    { name: "Parker Hayes", tribe: "Flame" },
    { name: "Quinn Sawyer", tribe: "Stone" },
    { name: "Renee Morgan", tribe: "Stone" },
    { name: "Seth Ramsey", tribe: "Stone" },
    { name: "Talia Brooks", tribe: "Stone" },
  ],
} as const;
