export const SURVIVOR_50 = {
  seasonKey: "SURVIVOR_50",
  castaways: [
    { name: "Colby Donaldson", tribe: "Vatu" },
    { name: "Stephenie LaGrossa Kendrick", tribe: "Vatu" },
    { name: "Quintavius 'Q' Burdette", tribe: "Vatu" },
    { name: "Genevieve Mushaluk", tribe: "Vatu" },
    { name: "Kyle Fraser", tribe: "Vatu" },
    { name: "Rizo Velovic", tribe: "Vatu" },
    { name: "Aubry Bracco", tribe: "Vatu" },
    { name: "Angelina Keeley", tribe: "Vatu" },
    { name: "Ozzy Lusth", tribe: "Cila" },
    { name: "Joe Hunter", tribe: "Cila" },
    { name: "Christian Hubicki", tribe: "Cila" },
    { name: "Rick Devens", tribe: "Cila" },
    { name: "Savannah Louie", tribe: "Cila" },
    { name: "Cirie Fields", tribe: "Cila" },
    { name: "Emily Flippen", tribe: "Cila" },
    { name: "Jenna Lewis-Dougherty", tribe: "Cila" },
    { name: "Benjamin 'Coach' Wade", tribe: "Kalo" },
    { name: "Kamilla Karthigesu", tribe: "Kalo" },
    { name: "Mike White", tribe: "Kalo" },
    { name: "Charlie Davis", tribe: "Kalo" },
    { name: "Tiffany Ervin", tribe: "Kalo" },
    { name: "Dee Valadares", tribe: "Kalo" },
    { name: "Jonathan Young", tribe: "Kalo" },
    { name: "Chrissy Hofbeck", tribe: "Kalo" },
  ],
} as const;
